import type {
  AdminInventoryRow,
  AdminSkuManagerRow,
  Membership,
  PartnerSharePageData,
  PartnerShareSheetDetail,
  ProductCategoryRow,
  RestockRequestRow,
  StaffInventoryRow,
} from "@/types/database";
import type { ReportAudit, ReportMovement, ReportRestock } from "@/components/reports-activity-lists";
import type { ReportsAreaDatum } from "@/components/reports-area-chart";

const organization = {
  organization_id: "00000000-0000-4000-8000-000000000001",
  organization_name: "Aero Training Store",
  organization_icon: "A",
  organization_slug: "aero-training",
};

export function demoMembership(role: "admin" | "staff"): Membership {
  return {
    ...organization,
    role,
    user_email: role === "admin" ? "admin@aero.training" : "staff@aero.training",
    full_name: role === "admin" ? "Aero Admin" : "Aero Staff",
    workspaces: [
      {
        ...organization,
        role,
        status: "active",
        user_email: role === "admin" ? "admin@aero.training" : "staff@aero.training",
        full_name: role === "admin" ? "Aero Admin" : "Aero Staff",
        last_accessed_at: new Date().toISOString(),
        is_last_workspace: true,
        created_at: new Date().toISOString(),
      },
    ],
  };
}

const groupedRows: AdminInventoryRow[] = [
  {
    sku_id: "11111111-1111-4111-8111-111111111111",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Whiskas Wet Pouch Bundle",
    variant: "Tuna 12x85g",
    sku_code: "WWP-TUNA-12",
    photo_path: null,
    photo_url: null,
    price: 29.9,
    variation_group_id: "99999999-9999-4999-8999-999999999999",
    variation_name: "Flavor",
    add_variation_images: true,
    quantity: 36,
    low_stock_qty: 8,
    max_stock_qty: 80,
    location_name: "Main Shelf",
    is_low_stock: false,
    is_out_of_stock: false,
    category_name: "Cat Food",
    supplier_name: "Aero Variation Supply",
    contact_name: "Maya",
    phone_raw: "012-220 7788",
    whatsapp_number: "60122207788",
  },
  {
    sku_id: "22222222-2222-4222-8222-222222222222",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Whiskas Wet Pouch Bundle",
    variant: "Salmon 12x85g",
    sku_code: "WWP-SALMON-12",
    photo_path: null,
    photo_url: null,
    price: 32.9,
    variation_group_id: "99999999-9999-4999-8999-999999999999",
    variation_name: "Flavor",
    add_variation_images: true,
    quantity: 18,
    low_stock_qty: 8,
    max_stock_qty: 80,
    location_name: "Main Shelf",
    is_low_stock: false,
    is_out_of_stock: false,
    category_name: "Cat Food",
    supplier_name: "Aero Variation Supply",
    contact_name: "Maya",
    phone_raw: "012-220 7788",
    whatsapp_number: "60122207788",
  },
  {
    sku_id: "33333333-3333-4333-8333-333333333333",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Whiskas Wet Pouch Bundle",
    variant: "Chicken 12x85g",
    sku_code: "WWP-CHICKEN-12",
    photo_path: null,
    photo_url: null,
    price: 29.9,
    variation_group_id: "99999999-9999-4999-8999-999999999999",
    variation_name: "Flavor",
    add_variation_images: true,
    quantity: 32,
    low_stock_qty: 8,
    max_stock_qty: 80,
    location_name: "Main Shelf",
    is_low_stock: false,
    is_out_of_stock: false,
    category_name: "Cat Food",
    supplier_name: "Aero Variation Supply",
    contact_name: "Maya",
    phone_raw: "012-220 7788",
    whatsapp_number: "60122207788",
  },
  {
    sku_id: "44444444-4444-4444-8444-444444444444",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Healthy Bites Treat Packs",
    variant: "200g Value Pack",
    sku_code: "HBT-200G",
    photo_path: null,
    photo_url: null,
    price: 16.9,
    variation_group_id: "88888888-8888-4888-8888-888888888888",
    variation_name: "Pack Size",
    add_variation_images: false,
    quantity: 11,
    low_stock_qty: 10,
    max_stock_qty: 60,
    location_name: "Main Shelf",
    is_low_stock: false,
    is_out_of_stock: false,
    category_name: "Treats",
    supplier_name: "PetSupply Co.",
    contact_name: "Leo",
    phone_raw: "012-345 6789",
    whatsapp_number: "60123456789",
  },
  {
    sku_id: "55555555-5555-4555-8555-555555555555",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Healthy Bites Treat Packs",
    variant: "100g Trial Pack",
    sku_code: "HBT-100G",
    photo_path: null,
    photo_url: null,
    price: 9.9,
    variation_group_id: "88888888-8888-4888-8888-888888888888",
    variation_name: "Pack Size",
    add_variation_images: false,
    quantity: 7,
    low_stock_qty: 10,
    max_stock_qty: 50,
    location_name: "Main Shelf",
    is_low_stock: true,
    is_out_of_stock: false,
    category_name: "Treats",
    supplier_name: "PetSupply Co.",
    contact_name: "Leo",
    phone_raw: "012-345 6789",
    whatsapp_number: "60123456789",
  },
  {
    sku_id: "66666666-6666-4666-8666-666666666666",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    product_name: "Cat Litter",
    variant: "10L",
    sku_code: "CL-10L-001",
    photo_path: null,
    photo_url: null,
    price: 24.9,
    variation_group_id: null,
    variation_name: null,
    add_variation_images: null,
    quantity: 23,
    low_stock_qty: 10,
    max_stock_qty: 60,
    location_name: "Main Shelf",
    is_low_stock: false,
    is_out_of_stock: false,
    category_name: "Litter",
    supplier_name: "Whisker & Co.",
    contact_name: "Ari",
    phone_raw: "019-876 5432",
    whatsapp_number: "60198765432",
  },
];

export const demoAdminRows: AdminInventoryRow[] = groupedRows;
export const demoStaffRows: StaffInventoryRow[] = groupedRows.map((row) => ({
  sku_id: row.sku_id,
  location_id: row.location_id,
  product_name: row.product_name,
  variant: row.variant,
  sku_code: row.sku_code,
  photo_path: row.photo_path,
  photo_url: row.photo_url,
  price: row.price,
  variation_group_id: row.variation_group_id,
  variation_name: row.variation_name,
  add_variation_images: row.add_variation_images,
  quantity: row.quantity,
  low_stock_qty: row.low_stock_qty,
  max_stock_qty: row.max_stock_qty,
  location_name: row.location_name,
  is_low_stock: row.is_low_stock,
  is_out_of_stock: row.is_out_of_stock,
  category_name: row.category_name,
}));

export const demoCategories: ProductCategoryRow[] = [
  { id: "cat-food", name: "Cat Food" },
  { id: "treats", name: "Treats" },
  { id: "litter", name: "Litter" },
];

export const demoSkuRows: AdminSkuManagerRow[] = demoAdminRows.map((row) => ({
  ...row,
  country: "MY",
}));

export const demoRestockRequests: RestockRequestRow[] = [
  {
    id: "restock-1",
    sku_id: "55555555-5555-4555-8555-555555555555",
    location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    status: "open",
    requested_qty: 24,
    current_qty_snapshot: 7,
    low_stock_qty_snapshot: 10,
    note: "Training request: reorder trial packs before weekend.",
    created_at: new Date().toISOString(),
    product_name: "Healthy Bites Treat Packs",
    sku_code: "HBT-100G",
    requested_by_name: "Aero Staff",
    requested_by_email: "staff@aero.training",
  },
];

export const demoPartnerSharePageData: PartnerSharePageData = {
  partners: [
    { id: "partner-1", name: "Whisker & Co.", contact_name: "Ari", phone_raw: "019-876 5432", whatsapp_number: "60198765432", notes: "Weekly sharing partner", archived_at: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ],
  categories: demoCategories,
  sheets: [
    {
      id: "sheet-1",
      partner_id: "partner-1",
      partner_name: "Whisker & Co.",
      location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      location_name: "Main Shelf",
      source_shop_name: "Aero Training Store",
      share_date: new Date().toISOString().slice(0, 10),
      auto_sync_with_main_store: false,
      status: "draft",
      item_count: 2,
      total_share_qty: 8,
      prepared_by_name: "Aero Admin",
      approved_by_name: null,
      sent_by_name: null,
      completed_by_name: null,
      stock_deducted_by_name: null,
      confirmed_at: null,
      sent_at: null,
      completed_at: null,
      stock_deducted_at: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};

export const demoPartnerShareDetails: PartnerShareSheetDetail[] = [
  {
    sheet: { ...demoPartnerSharePageData.sheets[0], organization_id: organization.organization_id },
    items: [
      { id: "share-item-1", sheet_id: "sheet-1", sku_id: "11111111-1111-4111-8111-111111111111", location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", product_name: "Whiskas Wet Pouch Bundle", variant: "Tuna 12x85g", sku_code: "WWP-TUNA-12", current_stock_snapshot: 36, photo_path: null, photo_url: null, supplier_name: "Aero Variation Supply", category_name: "Cat Food", share_qty: 5, remark: "Fast seller", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
      { id: "share-item-2", sheet_id: "sheet-1", sku_id: "66666666-6666-4666-8666-666666666666", location_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", product_name: "Cat Litter", variant: "10L", sku_code: "CL-10L-001", current_stock_snapshot: 23, photo_path: null, photo_url: null, supplier_name: "Whisker & Co.", category_name: "Litter", share_qty: 3, remark: "Bundle with wet food", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    ],
  },
];

export const demoReportChart: ReportsAreaDatum[] = [
  { month: "Jan", movement: 40 },
  { month: "Feb", movement: 62 },
  { month: "Mar", movement: 48 },
  { month: "Apr", movement: 76 },
  { month: "May", movement: 58 },
  { month: "Jun", movement: 91 },
];

export const demoReportMovements: ReportMovement[] = [
  { id: "move-1", skuId: "11111111-1111-4111-8111-111111111111", skuCode: "WWP-TUNA-12", productName: "Whiskas Wet Pouch Bundle", photoUrl: null, movementType: "add", quantityDelta: 12, quantityBefore: 24, quantityAfter: 36, reason: "Stock Adjustment", locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", locationName: "Main Shelf", actorRole: "admin", actorName: "Aero Admin", note: "Training stock received", createdAt: new Date().toISOString() },
  { id: "move-2", skuId: "55555555-5555-4555-8555-555555555555", skuCode: "HBT-100G", productName: "Healthy Bites Treat Packs", photoUrl: null, movementType: "deduct", quantityDelta: -5, quantityBefore: 12, quantityAfter: 7, reason: "Others", locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", locationName: "Main Shelf", actorRole: "staff", actorName: "Aero Staff", note: "Training shelf count", createdAt: new Date().toISOString() },
];

export const demoReportRestocks: ReportRestock[] = demoRestockRequests.map((request) => ({
  id: request.id,
  skuId: request.sku_id,
  skuCode: request.sku_code,
  productName: request.product_name,
  photoUrl: null,
  status: request.status,
  requestedQty: request.requested_qty,
  currentQty: request.current_qty_snapshot,
  lowStockQty: request.low_stock_qty_snapshot,
  requestedBy: request.requested_by_name ?? "Aero Staff",
  note: request.note,
  createdAt: request.created_at,
}));

export const demoReportAudits: ReportAudit[] = [
  { id: "audit-1", action: "tutorial_created", eventType: "training", entityType: "guide", entityLabel: "Tutorial walkthrough", actorRole: "admin", actorName: "Aero Admin", createdAt: new Date().toISOString(), beforeData: null, afterData: null, metadata: { lesson: "stock" } },
];
